version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: DockerfileDjango
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: DockerfileNode
    ports:
      - "3000:3000"
    depends_on:
      - web